---
title: "Text_TDA"
author: "Matt O'Reilly"
date: "1/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(nonlinearTseries)
library(TDAstats)
library(tidyverse)
library(dplyr)
library(readxl)
library(tm) #NLP
```


###Word Count Vectors
```{r}
text_data <- read_excel("./data/wordcount_vectors.xlsx")
text_vector_data <- text_data %>% select(wordcountvec)
#names <- text_data %>% select(category)
```

```{r}
wordvec_list <- c()
for (i in 1:nrow(text_vector_data)){
  text_vector_data[i,] <- removePunctuation(as.character(text_vector_data[i,]))
  x <- as.list(text_vector_data[i,])
  wordvec_list <- c(wordvec_list, x)
}

wordvec_df <- as.data.frame(wordvec_list)
wordvec_dfc <- as.character(wordvec_df)
wordvec_lst <- strsplit(wordvec_dfc, " ")    # Use " " if the values are separated by spaces
wordvec_lst <-sapply(wordvec_lst, as.integer)
size <- max(sapply(wordvec_lst, length))
wordvec_df <- data.frame(sapply(wordvec_lst, function(x) c(x, rep(NA, size - length(x)))))
#wordvec_df 
```

```{r}
betti_num_list <- list()
for (i in 1:ncol(wordvec_df)){
vec <- zoo::na.trim(wordvec_df[,i], is.na = "all") #Removes NA's from bottom of vector
text_vector_matrix <- data.matrix(vec)
tak <- buildTakens(text_vector_matrix,2,3)
hom <- calculate_homology(tak,return_df = TRUE) 
hom <- hom %>%
  mutate(persistence = death-birth) %>%
  mutate(persistent = ifelse(persistence > 0.1, 1,0))
hom_matrix <- tibble(hom) %>% select(dimension, persistent)
betti_num <- sum(hom$persistent == 1 & hom$dimension == 1)
betti_num_list <- append(betti_num_list, betti_num)
}
```


##TDA - Word Count Vectors

```{r}
#Tech / Col 1 / 4 1 dim holes iff persis == 1
vec1 <- zoo::na.trim(wordvec_df[,1], is.na = "all") #Removes NA's from bottom of vector
text_vector_matrix <- data.matrix(vec1)
tak <- buildTakens(text_vector_matrix,2,3)
hom <- calculate_homology(tak,return_df = TRUE) 
hom_matrix <- calculate_homology(tak,return_df = FALSE) 
bar <- plot_barcode(hom_matrix)
hom <- hom %>%
  mutate(persistence = death-birth) %>%
  mutate(persistent = ifelse(persistence > 0.4, 1,0))
hom_matrix <- tibble(hom) %>% select(dimension, persistent)
hom
hom_matrix <- tibble(hom_matrix) 
p1 <- hom_matrix[hom_matrix$persistent == '1',] 
betti_num <- sum(hom_matrix$persistent == 1 & hom_matrix$dimension == 1)
```

```{r}
#business / Col 2 / 2 1 dim holes iff persis == 1
vec2 <- zoo::na.trim(wordvec_df[,2], is.na = "all") #Removes NA's from bottom of vector 
text_vector_matrix <- data.matrix(vec2)
tak <- buildTakens(text_vector_matrix,2,3)
hom <- calculate_homology(tak,return_df = TRUE) 
hom_matrix <- calculate_homology(tak,return_df = FALSE) 
bar <- plot_barcode(hom_matrix)
hom <- hom %>%
  mutate(persistence = death-birth) %>%
  mutate(persistent = ifelse(persistence > 0.4, 1,0))
hom_matrix <- tibble(hom) %>% select(dimension, persistent)
hom
hom_matrix <- tibble(hom_matrix) 
p1 <- hom_matrix[hom_matrix$persistent == '1',] 
#text_homology<-rbind.data.frame(text_homology,p1)
bar
```

```{r}
#Sport / Col 3 / 3 1 dim holes iff persis == 1
vec3 <- zoo::na.trim(wordvec_df[,3], is.na = "all") #Removes NA's from bottom of vector 
text_vector_matrix <- data.matrix(vec3)
tak <- buildTakens(text_vector_matrix,2,3)
hom <- calculate_homology(tak,return_df = TRUE) 
hom_matrix <- calculate_homology(tak,return_df = FALSE) 
bar <- plot_barcode(hom_matrix)
hom <- hom %>%
  mutate(persistence = death-birth) %>%
  mutate(persistent = ifelse(persistence > 0.4, 1,0))
hom_matrix <- tibble(hom) %>% select(dimension, persistent)
hom
hom_matrix <- tibble(hom_matrix) 
p1 <- hom_matrix[hom_matrix$persistent == '1',] 
#text_homology<-rbind.data.frame(text_homology,p1)
bar
```
```{r}
#Entertainment / Col 5 / 4 1 dim holes iff persis == 1
vec5 <- zoo::na.trim(wordvec_df[,5], is.na = "all") #Removes NA's from bottom of vector 
text_vector_matrix <- data.matrix(vec5)
tak <- buildTakens(text_vector_matrix,2,3)
hom <- calculate_homology(tak,return_df = TRUE) 
hom_matrix <- calculate_homology(tak,return_df = FALSE) 
bar <- plot_barcode(hom_matrix)
hom <- hom %>%
  mutate(persistence = death-birth) %>%
  mutate(persistent = ifelse(persistence > 0.4, 1,0))
hom_matrix <- tibble(hom) %>% select(dimension, persistent)
hom
hom_matrix <- tibble(hom_matrix) 
p1 <- hom_matrix[hom_matrix$persistent == '1',] 
p1
#text_homology<-rbind.data.frame(text_homology,p1)
bar
```

```{r}
#Politics / Col 19 / 5 1 dim holes iff persis == 1
vec19 <- zoo::na.trim(wordvec_df[,19], is.na = "all") #Removes NA's from bottom of vector 
text_vector_matrix <- data.matrix(vec19)
tak <- buildTakens(text_vector_matrix,2,3)
hom <- calculate_homology(tak,return_df = TRUE) 
hom_matrix <- calculate_homology(tak,return_df = FALSE) 
bar <- plot_barcode(hom_matrix)
hom <- hom %>%
  mutate(persistence = death-birth) %>%
  mutate(persistent = ifelse(persistence > 0.4, 1,0))
hom_matrix <- tibble(hom) %>% select(dimension, persistent)
hom_matrix <- tibble(hom_matrix) 
hom
p1 <- hom_matrix[hom_matrix$persistent == '1',] 
p1
#text_homology<-rbind.data.frame(text_homology,p1)
bar
```


###Word Frequencies with Tfidf Vectors
```{r}
text_data <- read_excel("./data/freq_vectors.xlsx")
text_vector_data <- text_data %>% select(wordfreqvec)
```

```{r}
wordfreq_list <- c()
for (i in 1:nrow(text_vector_data)){
  x <- as.list(text_vector_data[i,])
  wordfreq_list <- c(wordfreq_list, x)
}

wordfreq_df <- as.data.frame(wordfreq_list)
wordfreq_dfc <- as.character(wordfreq_df)
wordfreq_dfc <- gsub("\\[|\\]", "", wordfreq_dfc)
wordfreq_lst <- strsplit(wordfreq_dfc, ", ")    # Use " " if the values are separated by spaces
wordfreq_lst <-sapply(wordfreq_lst, as.integer)
size <- max(sapply(wordfreq_lst, length))
wordfreq_df <- data.frame(sapply(wordfreq_lst, function(x) c(x, rep(NA, size - length(x)))))
wordfreq_df





```


```{r}
tech <- data.frame()
business <- data.frame()
sport <- data.frame()
entertainment <- data.frame()
politics <- data.frame()
text_homology <- data.frame()

#length(text_data['wordcountvec']
for (i in 1:ncol(word_vec_df)){
text_vector_matrix <- data.matrix(word_vec_df[,i])
tak <- buildTakens(text_vector_matrix,2,3)
#plot(tak)
hom <- calculate_homology(tak,return_df = TRUE) 
hom_matrix <- calculate_homology(tak,return_df = FALSE) 
bar <- plot_barcode(hom_matrix)
hom <- hom %>%
  mutate(persistence = death-birth) %>%
  mutate(persistent = ifelse(persistence > 0.1, 1,0))
hom_matrix <- tibble(hom) %>% select(dimension, persistent)
hom_matrix <- tibble(hom_matrix) 
p1 <- hom_matrix[hom_matrix$persistent == '1',] 
text_homology<-rbind.data.frame(text_homology,p1)
print(bar)
}

```

