---
title: "NLP_Example"
author: "Matt O'Reilly"
date: "3/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tm)
```


```{r}
song <- c("When raindrops - fell down from @ the sky", "The day you //left me, an angel #cried", "Oh, she cried, an angel cried","She cried...")
```

#Lowercase text and remove punctuation
```{r}
corpus <- VCorpus(VectorSource(song))
corpus <- tm_map(corpus, content_transformer(tolower))
corpus <- tm_map(corpus, removePunctuation)
for (i in 1:4) print (corpus[[i]]$content)
```

#Remove Stopwords
```{r}
corpus <- tm_map(corpus, removeWords, stopwords("english"))
for (i in 1:4) print (corpus[[i]]$content)
```
#Stem Document (Using Porter Stemming)
```{r}
corpus <- tm_map(corpus,stemDocument)
corpus <- tm_map(corpus, stripWhitespace)
for (i in 1:4) print (corpus[[i]]$content)

```

```{r}
terms <-DocumentTermMatrix(corpus,control = list(weighting = function(x) weightTfIdf(x, normalize = TRUE)))
as.matrix(terms)
```
```{r}
hom <- TDAstats::calculate_homology(terms)
TDAstats::plot_barcode(hom)
```

